name: Scheduled - alert prod diff

permissions: write-all

on:
  workflow_dispatch:
  schedule:
    # 8am UTC every day, will run against the default / main branch
    - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push updates to this repo
        run: |
          ./push.sh
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Checkout pushTest2! 
        uses: actions/checkout@v3
        with:
          repository: mjtalbot/pushTest2
          path: downstream/pushTest2
          token: ${{ secrets.PAT_GITHUB }}
          fetch-depth: 0

      - name: Push updates to pushTest2!
        run: |
          ./push_test_2.sh
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}